name: Android Build and Notify Teams

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK and Notify Teams
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Notify Microsoft Teams
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          APK_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -H "Content-Type: application/json" \
               -d '{
                 "@type": "MessageCard",
                 "@context": "http://schema.org/extensions",
                 "summary": "Android Build",
                 "themeColor": "0076D7",
                 "title": "✅ New Android Build Available",
                 "sections": [{
                   "activityTitle": "Build completed for `${{ github.repository }}`",
                   "facts": [
                     {"name": "Branch", "value": "${{ github.ref_name }}"},
                     {"name": "Commit", "value": "${{ github.sha }}"},
                     {"name": "View Build", "value": "[Click here]('"$APK_URL"')"}
                   ],
                   "markdown": true
                 }]
               }' \
               $TEAMS_WEBHOOK
