name: Android Build and Notify Teams

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK and Notify Teams
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Notify Microsoft Teams
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          APK_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          PAYLOAD=$(cat <<EOF
          {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "size": "Medium",
                      "weight": "Bolder",
                      "text": "✅ New Android Build Available"
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {
                          "title": "Repository",
                          "value": "${{ github.repository }}"
                        },
                        {
                          "title": "Branch",
                          "value": "${{ github.ref_name }}"
                        },
                        {
                          "title": "Commit",
                          "value": "${{ github.sha }}"
                        }
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "View Build",
                      "url": "${APK_URL}"
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.2"
                }
              }
            ]
          }
          EOF
          )
          curl -H "Content-Type: application/json" -d "$PAYLOAD" $TEAMS_WEBHOOK